### ISSUE TITLE
Uncss with laravel files?

### ISSUE THREAD

**Issue by leeovery** [hosmelq/laravel-elixir-uncss#2]
Hey

Thanks for sharing this package - saves me doing it myself! :)

I just wanted to ask - how are you using this with a laravel site? Are you pointing the html to the blade cache files?

Ive tried pointing uncss to the resources/view dir but it misses loads of styles and messes up the css file.

How are you making this work?

Thanks again!!
Lee

**Comment by leogoncalves** [comment]
+1

**Comment by blackfyre** [comment]
I'm using Laravel homestead for development, and the mix below worked for me:

``` javascript

mix.uncss('../../../public/css/home.css', { /* Since I use sass, the default path doesn't work for me */
  html: ['http://your.app/']
},'public/css-trim');

```

To add another page, simply create a new mix with the parameters modified accordingly.

**Comment by hosmelq** [comment]
Sorry for too late, i'm so busy right now. This is how i used in a laravel site.

``` js
mix.uncss('files.css', {
  html: ['http://app.dev']
});
```

Also you can add a third parameter for the `output` like @blackfyre's example and a fourth parameter to specify de `baseDir`

**Comment by hosmelq** [comment]
I'll close this. Feel free to discuss it.

**Comment by johnylaravel** [comment]
Hey, great feature! How to set this up for Laravel Mix?

**Comment by hosmelq** [comment]
Mix doesn't have any plugin ecosystem. You can use [mix.webpackConfig](https://laravel.com/docs/5.4/mix#custom-webpack-configuration) to add any custom functionality and use something like https://github.com/vseventer/uncss-webpack-plugin.

**Comment by johnylaravel** [comment]
Thanks man @hosmelq
